global:
  scrape_interval: 15s

scrape_configs:
  - job_name: app
    static_configs:
      - targets:
          - host.docker.internal:8082

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - host.docker.internal:9093