
# Database settings
database:
  url: "mongodb://root:secret@localhost:27017/catalog?retryWrites=true&w=majority&authSource=admin"
  db: "catalog"
  timeout: 5

# Server settings
server:
  host: "localhost"
  port: ":8082"
